version: "2"
services:
    web:
        image: nginx:latest
        ports:
        - "80:80"
        volumes:
        - ./:/www
        - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
        - php
    php:
        build: ""
        volumes:
        - ./:/www